# Generated by Django 3.1.6 on 2021-06-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='calorieAmount',
            field=models.DecimalField(decimal_places=3, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbAmount',
            field=models.DecimalField(decimal_places=3, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='fatAmount',
            field=models.DecimalField(decimal_places=3, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='food',
            name='proteinAmount',
            field=models.DecimalField(decimal_places=3, max_digits=7, null=True),
        ),
    ]
