# Generated by Django 3.2.4 on 2021-06-23 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0004_auto_20210620_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
