# Generated by Django 3.2.4 on 2021-06-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0005_remove_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='calorieAmount',
        ),
        migrations.RemoveField(
            model_name='food',
            name='carbAmount',
        ),
        migrations.RemoveField(
            model_name='food',
            name='fatAmount',
        ),
        migrations.RemoveField(
            model_name='food',
            name='proteinAmount',
        ),
        migrations.RemoveField(
            model_name='food',
            name='weightofItem',
        ),
        migrations.AddField(
            model_name='food',
            name='calories',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='carbs',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='fats',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='proteins',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
