# Generated by Django 3.2.4 on 2021-06-25 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0007_alter_food_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='category',
            new_name='food_category',
        ),
    ]
