# Generated by Django 3.2.4 on 2021-06-26 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0011_auto_20210626_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cc.customer'),
        ),
    ]
