# Generated by Django 3.1.6 on 2021-06-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0014_auto_20210630_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/static/images/user.png', null=True, upload_to=''),
        ),
    ]
