# Generated by Django 3.2.4 on 2021-07-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0017_auto_20210630_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
